### ISSUE TITLE
set PORT=3000 Page 75-76 on windows didn't work for me

### ISSUE THREAD

**Issue by chrismarksus** [bootstrapping-microservices/chapter-2#2]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.1

I needed to use `$Env:PORT = 3000` in the VSCode terminal powershell window

**Comment by ashleydavis** [comment]
Oh ok, thanks for letting me know.

I'm sorry I didn't think to give instructions for Powershell because I never use it.

I use the regular Windows command prompt or the Ubuntu WSL2 command prompt.
