### ISSUE TITLE
Listing 2.2 do not correspond to file 

### ISSUE THREAD

**Issue by juanfreitaschama** [bootstrapping-microservices/chapter-2#3]
On Chapter 2, the listing 2.2 figure on the book do not correspond to the file [https://github.com/bootstrapping-microservices/chapter-2/blob/master/example-1/package.json](https://github.com/bootstrapping-microservices/chapter-2/blob/master/example-1/package.json  ).

License and scripts section are different from the book

**Comment by ashleydavis** [comment]
Yes it's a bit different.

The licence for the code has changed to MIT.

The concept of the "start" script hasn't been introduced at that point in the book (even though it's implemented for all the examples). Read on in the book to learn more about the "start" script.

Thanks for your feedback.
